---
    - name: Launching Azure virtual machine
      azure_rm_virtualmachine:

        # subscription_id: "{{ connection.subscription_id | b64decode }}"
        # tenant: "{{ connection.tenant | b64decode }}"
        # client_id: "{{ connection.client_id | b64decode }}"
        # secret: "{{ connection.secret | b64decode }}"
        resource_group: "{{ resource_config.group_name }}"
        location: "{{ resource_config.region }}"
        name: "{{ resource_config.vm_name }}"
        vm_size: "{{ resource_config.flavor.name }}"
        admin_username: "{{ resource_config.template_username }}"
        admin_password: "{{ resource_config.template_password }}"
        virtual_network_name: "{{ resource_config.vnet_name }}"
        subnet_name: "{{ resource_config.subnet }}"
        image:
            offer: "{{ resource_config.template_name }}"
            publisher: "OpenLogic"
            sku: "7.4"
            version: latest
      
      register: facts



    - name: To display all metadata of azure virtual machine
      debug:
        msg: "{{ facts }}"


    - name: Registering the IP address while parsing metadata
      shell: echo "{{ facts.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress }}"
      register: azure_ipaddress

    - name: Ip address of azure virtual machine
      debug:
        msg: "{{ azure_ipaddress.stdout_lines[0] }}"
