---
    - name: create an instance
      gcp_compute_instance:
        state: present
        name: "{{ resource_config.gcp.vm_name }}"
        machine_type: "{{ resource_config.gcp.vm_flavor }}"
        disks:
          - auto_delete: true
            boot: true
            source: "{{ disk }}"
        network_interfaces:
            - network: "{{ network }}"
              access_configs:
                - name: 'External NAT'
                  nat_ip: "{{ address }}"
                  type: 'ONE_TO_ONE_NAT'
        zone: "{{ resource_config.gcp.zone }}"
        project: "{{ resource_config.gcp.gcp_project }}"
        auth_kind: "{{ resource_config.gcp.gcp_cred_kind }}"
#         service_account_file: "{{ resource_config.gcp.gcp_cred_file }}"
        scopes:
          - https://www.googleapis.com/auth/compute
      register: instance


    - name:  To display metadata of GCP instance
      debug:
        msg: "{{ instance }}"

    - name: To get IP address
      debug: 
          msg: "{{ address.address }}"
