---

   - name: create a network
     gcp_compute_network:
        name: "{{ resource_config.gcp.network_instance }}"
        project: "{{ resource_config.azure.gcp_project }}"
        auth_kind: "{{ resource_config.azure.gcp_cred_kind }}"
        service_account_file: "{{ resource_config.azure.gcp_cred_file }}"
        scopes:
            - https://www.googleapis.com/auth/compute
        state: present
     register: network
